Add topic name to debug output
MaterializeInc/datagen pull request #7
Opened 2023-02-01 09:07 UTC by bobbyiliev

## What type of PR is this? (check all applicable)

- [x] ♻️ Refactor
- [ ] ✨ Feature
- [x] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Description

Closes #5 

## Related Tickets & Documents

## Added to documentation?

- [ ] 📜 readme
- [x] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

2023-02-03 17:25 UTC, chuck-alt-delete commented
I'm seeing the topic name, which means this PR is probably good to go, but I think it uncovers why I was confused in the first place. When using a sql schema file, eg:

```sql
CREATE TABLE "ecommerce"."products" ...
```

I would expect the topic name to be `ecommerce.products` based on the fully qualified table name, but it looks like it's just `products`.

I think the offending line is here in src/schemas/parseSqlSchema.js:

```javascript
        let schema = {
            tableName: table.table[0].table,
            columns: []
        };
```
After some experimenting, I believe this would work to get the fully qualified table name and use that as the topic name:

```javascript
tableName: Object.values(table.table[0]).filter(x => x).join(".")
```

The filter is to filter out null values if that array contains any.

2023-02-03 17:25 UTC, chuck-alt-delete requested changes
See above

2023-02-04 16:50 UTC, bobbyiliev commented
Sweet! I like that idea! Just updated the topic name to use the full table name!

2023-02-04 17:54 UTC, chuck-alt-delete approved these changes

2023-02-04 17:54 UTC, merged