Fix infinite loop problem
MaterializeInc/datagen pull request #70
Opened 2023-03-09 17:41 UTC by bobbyiliev

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [x] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Description

Fixing the bug noticed during the weekly demo

## Related Tickets & Documents

N/A

## Added to documentation?

- [ ] 📜 readme
- [x] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

2023-03-09 17:49 UTC, chuck-alt-delete requested changes

2023-03-09 17:49 UTC, chuck-alt-delete commented on datagen.ts
> +            '-n, --number <number>',
could this be `<int>` instead?

2023-03-09 18:26 UTC, chuck-alt-delete commented on datagen.ts
> +            '-n, --number <number>',
```suggestion
            '-n, --number <int>',
```

2023-03-09 18:26 UTC, bobbyiliev commented on datagen.ts
> +            '-n, --number <number>',
Yep good point!

2023-03-09 18:26 UTC, chuck-alt-delete approved these changes

2023-03-10 02:45 UTC, chuck-alt-delete commented
I’m going to go ahead and merge so I can get this running for an experiment

2023-03-10 02:45 UTC, merged